
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t trickmaster23/docker-cicd-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true trickmaster23/docker-cicd-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-cicd-aws"
  env: "Dockercicdaws-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-088651691235"
  bucket_path: "docker-cicd-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key:
    secure: $AWS_SECRET_KEY

