language: node_js
node_js:
  - "8"

services:
  - docker

  before_install:
    - docker build -t trickmaster23/docker-cicd-aws -f Dockerfile.dev .


cache: yarn
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
  - npm run test:dev